Bug 1686645 [wpt PR 27181] - [DOMException] add test cases of error names table, a=testonly
Automatic update from web-platform-tests
DOMException: test code mapping for all error names

In particular, this tests the deprecated ones, some removed ones, and some newer error names which intentionally don't have legacy error codes. See also https://github.com/heycam/webidl/pull/946.

Closes #27151.
--

wpt-commits: 93c6faceda56025f1c96c0155990bf1d231dac9c
wpt-pr: 27181