Bug 1733034 - Fix unreachable-code warning in dom/media. r=padenot
dom/media/gtest/TestMediaDataEncoder.cpp:199:16: error: code will never be executed [-Werror,-Wunreachable-code]
        result = Some(false);
               ^

`FAIL()` expands to an expression that starts with `return`, so the code
coming after it never runs.

Differential Revision: https://phabricator.services.mozilla.com/D126873