Bug 1135535 part 3 - Fix C4258 definition ignored warnings and mark it an error in js/src on MSVC. r=luke
Fix warnings:
js\src\vm/UnboxedObject.cpp(212) : error C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        js\src\vm/UnboxedObject.cpp(209) : definition of 'i' ignored
        js\src\vm/UnboxedObject.cpp(204) : definition of 'i' used
js\src\vm/UnboxedObject.cpp(213) : error C4258: 'i' : definition from the for loop is ignored; the definition from the enclosing scope is used
        js\src\vm/UnboxedObject.cpp(209) : definition of 'i' ignored
        js\src\vm/UnboxedObject.cpp(204) : definition of 'i' used

--HG--
extra : rebase_source : 8ac8533686614faac97c7e58c1a014fae24f067c
extra : source : 1c10edf1b22a90eb60dfeb7557043a9d3e71d90d