Bug 1749473 - fix autodoc import warning r=sylvestre DONTBUILD
NameError: name 'self' is not defined

Depends on D196011

Differential Revision: https://phabricator.services.mozilla.com/D196012