Bug 1733034 - Fix unused-const-variable warning in dom/base/BodyStream.cpp. r=smaug
dom/base/BodyStream.cpp:21:22: error: unused variable 'kStreamTransportServiceCID' [-Werror,-Wunused-const-variable]
static NS_DEFINE_CID(kStreamTransportServiceCID, NS_STREAMTRANSPORTSERVICE_CID);
                     ^

Differential Revision: https://phabricator.services.mozilla.com/D126867