Bug 1765474 - Fix unused-but-set-variable warning in nsSprocketLayout.cpp. r=emilio
layout/xul/nsSprocketLayout.cpp:1116:14: error: variable 'pass' set but not used [-Werror,-Wunused-but-set-variable]
    for (int pass = 1; true == limit; pass++) {
             ^

Differential Revision: https://phabricator.services.mozilla.com/D144143