Bug 1735257 - Fix unused-but-set-variable warning in MacroAssembler-arm.cpp. r=jandem
MacroAssembler-arm.cpp:4121:11: error: variable 'diffG' set but not used [-Werror,-Wunused-but-set-variable]

Differential Revision: https://phabricator.services.mozilla.com/D128157