Bug 1635671 - Upgrade typename to 1.12.0. r=emilio
When building in some configurations of rustc (e.g. i386 without SSE), building Firefox fails with, among other things:
```
error[E0428]: the name `U1024` is defined multiple times
```

This comes from the typenum library. The issue was fixed in https://github.com/paholg/typenum/commit/14a3322d1081fd63d5eb44bf8ab8f90676208228, so all it takes is an upgrade of the crate.

Differential Revision: https://phabricator.services.mozilla.com/D74005