Bug 1732208 - Silence the unused-but-set-variable warning in xpcom. r=xpcom-reviewers,mccr8
xpcom/tests/gtest/TestAvailableMemoryWatcherWin.cpp(130,22): error: variable 'x' set but not used [-Werror,-Wunused-but-set-variable]
    volatile uint8_t x = 0;
                     ^
xpcom/tests/gtest/TestAvailableMemoryWatcherWin.cpp(152,12): error: variable 'consumed' set but not used [-Werror,-Wunused-but-set-variable]
    size_t consumed = 0;
           ^
xpcom/tests/gtest/TestSTLWrappers.cpp:48:7: error: variable 'rv' set but not used [-Werror,-Wunused-but-set-variable]
  int rv = 1;
      ^

Differential Revision: https://phabricator.services.mozilla.com/D126462