Bug 1562667 - P4b - Disable jsref test for Atomic on Nightly; r=lth,jorendorff
After enabling the perf for SAB by default on Nightly, some jsreftests fail.
And they all have log like:
tests/test262/shell.js:492: Error: Agents not available item 1

It seems that there are some issues on test262 shell, so the plan of this patch
is to disable these tests and open another follow-up ticket to re-enable them.
So that we could check the impact of enable the perf for SAB without enabling
the functionality of being postMessage'ed on Nightly users.

Differential Revision: https://phabricator.services.mozilla.com/D53966