Bug 1822982 [wpt PR 39049] - Fix MathML Python code to conform to the PEP 8 style guide, a=testonly
Automatic update from web-platform-tests
Fix MathML Python code to conform to the PEP 8 style guide

This commit fixes PEP 8 errors reported by `check-webkit-style` script:

```
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/largeop.py:59:  continuation line under-indented for hanging indent  [pep8/E121] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/mathvariant-transforms.py:75:  expected 2 blank lines, found 1  [pep8/E302] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/mathvariant-transforms.py:103:  missing whitespace around operator  [pep8/E225] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/mathvariant-transforms.py:176:  expected 2 blank lines after class or function definition, found 1  [pep8/E305] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy-centered-on-baseline.py:28:  at least two spaces before inline comment  [pep8/E261] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy-centered-on-baseline.py:29:  at least two spaces before inline comment  [pep8/E261] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy-centered-on-baseline.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy-centered-on-baseline.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy-centered-on-baseline.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy-centered-on-baseline.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy.py:28:  at least two spaces before inline comment  [pep8/E261] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy.py:29:  at least two spaces before inline comment  [pep8/E261] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/stretchy.py:31:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:174:  expected 2 blank lines, found 1  [pep8/E302] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:174:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:174:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:174:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:174:  unexpected spaces around keyword / parameter equals  [pep8/E251] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:189:  missing whitespace around arithmetic operator  [pep8/E226] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:189:  missing whitespace around arithmetic operator  [pep8/E226] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:195:  expected 2 blank lines, found 1  [pep8/E302] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:200:  the backslash is redundant between brackets  [pep8/E502] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/mathml/tools/utils/mathfont.py:206:  the backslash is redundant between brackets  [pep8/E502] [5]
```

--

wpt-commits: 3a3453c62176c97ab51cd492553c2dacd24366b1
wpt-pr: 39049