Bug 1794520 - Mark more build errors as errors. r=releng-reviewers,jcristau
The current regexp for build errors catches things like:
    Maybe.h:847:1: error: mutex 'forward(aArgs)' is still held at the end of function
but not things like:
    Unified_cpp_dom_base0.o904: error: Opaque pointers are only supported in -opaque-pointers mode
or:
    libnssutil3.so: error: undefined reference to '__tsan_memcpy'

In those currently uncovered cases, the first error message recognized
as an error is something like:
    [/builds/worker/checkouts/gecko/config/rules.mk:540: XUL] Error 1
or
    [/builds/worker/checkouts/gecko/config/makefiles/rust.mk:499: force-cargo-program-build] Error 101

which are too generic and don't help to pinpoint relevant bugs in the
treeherder UI.

Differential Revision: https://phabricator.services.mozilla.com/D159006