Bug 1543266 [wpt PR 16155] - [WPT] Fix JSON decoding errors in referrer-policy on Safari, a=testonly
Automatic update from web-platform-tests
[WPT] Fix JSON decoding errors in referrer-policy on Safari

In referrer-policy tests, image.py encodes information such as
request headers into pixel values and the tests decode the pixels
back to JSON using canvas.
However on wpt.fyi on Safari this decoding flakily fails with
SyntaxError: JSON Parse error: Unexpected identifier "z".

This is probably because pixel values on canvas are
affected by color profiles.
This CL encodes one bit per one color channel in a pixel
as 0 or 255 (rather than 8 bits per channel as 0-255), so that
small changes to pixel values don't affect decoding result.

Bug: 906850
Change-Id: Id14c73289592d729d92f710a7436a661c54b16f5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1546367
Reviewed-by: Jochen Eisinger <jochen@chromium.org>
Commit-Queue: Hiroshige Hayashizaki <hiroshige@chromium.org>
Cr-Commit-Position: refs/heads/master@{#647918}

--

wpt-commits: d524f330e260695315b7e0214e60c24d0a4c1e80
wpt-pr: 16155