servo: Merge #19440 - Added explicit UTF-8 encoding to test-perf (from asajeffrey:test-perf-utf8); r=jdm
<!-- Please describe your changes on the following line: -->

Added explicit UTF-8 encoding to test-perf, to try to avoid:
```
Traceback (most recent call last):
  File "runner.py", line 371, in <module>
    main()
  File "runner.py", line 361, in main
    save_result_csv(results, args.output_file, testcases, args.runs, args.base)
  File "runner.py", line 287, in save_result_csv
    writer.writerows(results)
  File "/usr/lib/python3.4/csv.py", line 159, in writerows
    return self.writer.writerows(rows)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 101-107: ordinal not in range(128)
```
http://build.servo.org/builders/linux-nightly/builds/526/steps/test/logs/stdio

---
<!-- Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data: -->
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes do not require tests because this is test infrastructure

<!-- Also, please make sure that "Allow edits from maintainers" checkbox is checked, so that we can help you if you get stuck somewhere along the way.-->

<!-- Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. -->

Source-Repo: https://github.com/servo/servo
Source-Revision: b7bb6ffbb85aed4e94f36a71fac112ae64d46911