servo: Merge #19017 - Print the full path for errors occurring in the servo crate (from tigercosmos:test); r=jdm
<!-- Please describe your changes on the following line: -->
`Cargo` will print the path where it runs.
Origin python script `cd` into the crate folder, so the root path is set in  the crate.
Now I use `--manifest-path PATH` to `cargo build`, so the root path is at `servo`.

Origin path in error message:
```
error: expected one of `!` or `::`, found `#`
  --> lib.rs:24:1
```

Now it would be:
```
error: expected one of `!` or `::`, found `use`
  --> ports/geckolib/glue.rs:11:1
```

---
<!-- Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data: -->
- [X] `./mach build -d` does not report any errors
- [X] `./mach test-tidy` does not report any errors
- [X] These changes fix #9895 (github issue number if applicable).

<!-- Either: -->
- [ ] There are tests for these changes OR
- [ ] These changes do not require tests because _____

<!-- Also, please make sure that "Allow edits from maintainers" checkbox is checked, so that we can help you if you get stuck somewhere along the way.-->

<!-- Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. -->

Source-Repo: https://github.com/servo/servo
Source-Revision: 4df647ed758730dd82a3eae5e78c296e495239d5

--HG--
extra : subtree_source : https%3A//hg.mozilla.org/projects/converted-servo-linear
extra : subtree_revision : c56cbdaf45e2d8c9bc4a27d13801cd5011f7be1d