Bug 1765474 - Fix unused-but-set-variable warning in TestBaseProfiler.cpp. r=gerald
mozglue/tests/TestBaseProfiler.cpp:2188:12: error: variable 'chunk1ReuseCount' set but not used [-Werror,-Wunused-but-set-variable]
  unsigned chunk1ReuseCount = 0;
           ^

Differential Revision: https://phabricator.services.mozilla.com/D144146