Bug 1587220 [wpt PR 19583] - Using device serial when using adb., a=testonly
Automatic update from web-platform-tests
Using device serial when using adb.

The Android device serial number, specified by the --device-serial
command-line option, was unused by the android_webview wptrunner.
This resulted in adb failing with the following error:

    adb wait-for-device
    error: more than one device/emulator

Bug: None
Change-Id: I85e236297d7e83950ac26a9283bdad4ef642d62c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1845486
Commit-Queue: Chris Mumford <cmumford@google.com>
Reviewed-by: Robert Ma <robertma@chromium.org>
Cr-Commit-Position: refs/heads/master@{#704747}

--

wpt-commits: 0e1c5dfb856eac565d794b2e831ce3e10cdd06f6
wpt-pr: 19583