Bug 1407289 Move classes from renderer11_utils.h r=jgilbert,Lenzak
It's illegal to use a method of a forward declared class

libANGLE/renderer/d3d/d3d11/renderer11_utils.h:207:31: error: invalid use of incomplete type 'class rx::Renderer11'
               ANGLE_TRY(renderer->allocateResource(desc, initData, &mResource));

However we cannot simply include Renderer11.h because Renderer11.h includes renderer11_utils.h

If we put the LazyX classes into Renderer11.h however, we can
change the include on the few places they are used with minimal impact.

MozReview-Commit-ID: 8Wf4Xbi7vAP

--HG--
extra : rebase_source : 984601e08f88342c8f5b75f9d43af3e666598855