Bug 1732208 - Silence the unused-but-set-variable warning in gfx. r=gfx-reviewers,nical
gfx/2d/SourceSurfaceD2D1.cpp(201,20): error: variable 'options' set but not used [-Werror,-Wunused-but-set-variable]
  D2D1_MAP_OPTIONS options;
                   ^
gfx/thebes/gfxDWriteFontList.h(269,13): error: variable 'hr' set but not used [-Werror,-Wunused-but-set-variable]
    HRESULT hr = S_OK;
            ^
gfx/thebes/gfxGDIFontList.cpp(1020,12): error: variable 'cmapLoaded' set but not used [-Werror,-Wunused-but-set-variable]
      bool cmapLoaded = false;
           ^
gfx/thebes/gfxMacPlatformFontList.mm:1771:10: error: variable 'isStandardFace' set but not used [-Werror,-Wunused-but-set-variable]
    bool isStandardFace = false;
         ^
gfx/thebes/gfxPlatformFontList.cpp(1064,18): error: variable 'rejectedFallbackVisibility' set but not used [-Werror,-Wunused-but-set-variable]
  FontVisibility rejectedFallbackVisibility = FontVisibility::Unknown;
                 ^
gfx/vr/service/OculusSession.cpp(1329,12): error: variable 'bNewController' set but not used [-Werror,-Wunused-but-set-variable]
      bool bNewController = false;
           ^

Differential Revision: https://phabricator.services.mozilla.com/D126454