Bug 1770845 - Fix non-unified build error in gfx/thebes/gfxMacPlatformFontList.mm. r=jfkthame,gfx-reviewers,lsalzman
This build error was a regression from bug 1743170. The code that used kDeprecatedFontFamilies was wrapped with #ifdef USE_DEPRECATED_FONT_FAMILY_NAMES, but the definition of kDeprecatedFontFamilies wasn't so the compiler thinks kDeprecatedFontFamilies is unused.

gfx/thebes/gfxMacPlatformFontList.mm:92:28: error: unused variable 'kDeprecatedFontFamilies' [-Werror,-Wunused-const-variable]
constexpr nsLiteralCString kDeprecatedFontFamilies[] = {

Differential Revision: https://phabricator.services.mozilla.com/D147115