Bug 1859066 [wpt PR 42542] - Tests for TypeErrors in AudioWorkletGlobalScope.registerProcessor(), a=testonly
Automatic update from web-platform-tests
Tests for TypeErrors in AudioWorkletGlobalScope.registerProcessor()

This CL add a test to verify TypeErrors that are thrown from
reigsterProcessor() method. It checks two cases:
 - When a given parameter is not a Function
 - When a given parameter is not a constructor

Bug: 1078902
Change-Id: Iba312bb558622ba68bcf850310c5cd87fa1d8655
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4939970
Commit-Queue: Hongchan Choi <hongchan@chromium.org>
Reviewed-by: Sina Firoozabadi <sinafirooz@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1211158}

--

wpt-commits: 010fed9cf8f72f6c575d9334f50a057585bc989e
wpt-pr: 42542