Bug 1754111 part 2: Fix non-unified build errors in layout/printing, and mark it as safe to build in non-unified mode. r=emilio
The previous patch in this series fixed some sources of non-unified build errors for this directory, and this patch here fixes the only remaining one, which is:

layout/printing/nsPrintJob.cpp:584:22: error: use of undeclared identifier 'do_CreateInstance'

This API is provided by nsComponentManagerUtils.h, which is the include I'm adding here.

Depends on D138096

Differential Revision: https://phabricator.services.mozilla.com/D138097