Bug 1670879 [wpt PR 26073] - Revert "Use a single, consistent path to update stage parameters.", a=testonly
Automatic update from web-platform-tests
Revert "Use a single, consistent path to update stage parameters."

This reverts commit e94960c9ac81f36bfeba2bdebe2c2714933a92da.

Reason for revert:
Windows build start failing since this build:
https://ci.chromium.org/p/chrome/builders/ci/win64-builder-perf/231735

Error message:
[8250/14154] CXX obj/device/vr/vr/oculus_device.obj
FAILED: obj/device/vr/vr/oculus_device.obj
...
../../device/vr/oculus/oculus_device.cc(69,17): error: no member named 'stage_parameters' in 'device::mojom::VRDisplayInfo'
  display_info->stage_parameters = mojom::VRStageParameters::New();
  ~~~~~~~~~~~~~~^
../../device/vr/oculus/oculus_device.cc(77,17): error: no member named 'stage_parameters' in 'device::mojom::VRDisplayInfo'
  display_info->stage_parameters->mojo_from_floor = mojo_from_floor;
  ~~~~~~~~~~~~~~^
../../device/vr/oculus/oculus_device.cc(81,17): error: no member named 'stage_parameters' in 'device::mojom::VRDisplayInfo'
  display_info->stage_parameters->bounds =
  ~~~~~~~~~~~~~~^

Original change's description:
> Use a single, consistent path to update stage parameters.
>
> Removes stage_parameters from VRDisplayInfo and updates the XR frame
> request loop to exchange an stage_parameters_id to indicate what version
> of the parameters the session has so that only updates need to be sent.
>
> Part of an ongoing process to remove VRDisplayInfo entirely.
>
> Bug: 998146
> Change-Id: I6f41dc2426b529694903d1e46cdadc16841b2b37
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2460976
> Commit-Queue: Brandon Jones <bajones@chromium.org>
> Reviewed-by: Chris Palmer <palmer@chromium.org>
> Reviewed-by: Alexander Cooper <alcooper@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#815903}

TBR=palmer@chromium.org,bajones@chromium.org,alcooper@chromium.org

Change-Id: Ic7073de29891c16d5a62f88bb6672e8338b5ece2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 998146
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2464348
Reviewed-by: Wenbin Zhang <wenbinzhang@google.com>
Commit-Queue: Wenbin Zhang <wenbinzhang@google.com>
Cr-Commit-Position: refs/heads/master@{#815923}

--

wpt-commits: 6bdfd63de5ddf832202409a18fe5822011667d7b
wpt-pr: 26073