bewildered BeOS 5.0 Depend on 06/03 10:47 Build Error Summary
c++ -o nsBookmarksService.o -c -DOSTYPE=\"BeOS5.0\" -DOSARCH=\"BeOS\" -DMOZ_REFLOW_PERF -DMOZ_REFLOW_PERF_DSP -DOJI   -I../../../../dist/include -I../../../../dist/include -I/boot/home/tinderbox/BeOS_5.0_Depend/mozilla/obj-i686-pc-beos/dist/include/nspr         -fPIC   -frtti -fno-exceptions -Wall -Wconversion -Wpointer-arith -Wbad-function-cast -Wcast-align -Woverloaded-virtual -Wsynth -Wno-multichar -Wno-ctor-dtor-privacy -pedantic -Wno-long-long -pipe  -DDEBUG -DDEBUG_cltbld -DTRACING -g  -DMOZILLA_CLIENT -include ../../../../config-defs.h -Wp,-MD,.deps/nsBookmarksService.pp /boot/home/tinderbox/BeOS_5.0_Depend/mozilla/xpfe/components/bookmarks/src/nsBookmarksService.cpp
/boot/home/tinderbox/BeOS_5.0_Depend/mozilla/xpfe/components/bookmarks/src/nsBookmarksService.cpp: In method `nsresult nsBookmarksService::ReadBookmarks()':
/boot/home/tinderbox/BeOS_5.0_Depend/mozilla/xpfe/components/bookmarks/src/nsBookmarksService.cpp:4112: no matching function for call to `BookmarkParser::SetIEFavoritesRoot (nsCString)'
/boot/home/tinderbox/BeOS_5.0_Depend/mozilla/xpfe/components/bookmarks/src/nsBookmarksService.cpp:403: candidates are: BookmarkParser::SetIEFavoritesRoot(nsCString &) <near match>
make[5]: *** [nsBookmarksService.o] Error 1

picky compiler. i'm amazed that any of the code in there works. this is a bustage fix that will only affect XP_BEOS.