Bug 1732208 - Silence the unused-but-set-variable warning in widget. r=cmartin
widget/windows/nsAppShell.cpp(685,10): error: variable 'uiMessage' set but not used [-Werror,-Wunused-but-set-variable]
    bool uiMessage = false;
         ^
widget/windows/TaskbarPreview.cpp(370,11): error: variable 'hr' set but not used [-Werror,-Wunused-but-set-variable]
  HRESULT hr;
          ^

Differential Revision: https://phabricator.services.mozilla.com/D126461