Bug 1599160 - Fix build error with nsTHashtable<const SheetLoadDataHashKey>. r=froydnj
Trying to use nsTHashtable<SheetLoadDataHashKey> yields the following
error:

   0:01.28 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/nsTHashtable.h:288:8: error: multiple overloads of 'RemoveEntry' instantiate to the same signature 'void (mozilla::SheetLoadDataHashKey *)'
   0:01.28   void RemoveEntry(EntryType* aEntry) { mTable.RemoveEntry(aEntry); }
   0:01.28        ^
   0:01.28 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/mozilla/css/Loader.h:600:38: note: in instantiation of template class 'nsTHashtable<mozilla::SheetLoadDataHashKey>' requested here
   0:01.28   nsTHashtable<SheetLoadDataHashKey> mLoadsPerformed;
   0:01.28                                      ^
   0:01.28 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/nsTHashtable.h:264:8: note: previous declaration is here
   0:01.28   void RemoveEntry(KeyType aKey) {

I tried and failed to std::enable_if my way to victory, but then
realized I could probably use nsTHashtable<const SheetLoadDataHashKey>,
so that the compiler wouldn't complain about the overload (they're
identical, so they don't really matter).

But doesn't work either, unless I have this patch, because:

    0:12.57 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/nsTHashtable.h:504:36: error: call to implicitly-deleted copy constructor of 'const mozilla::SheetLoadDataHashKey'
    0:12.57   new (mozilla::KnownNotNull, aTo) EntryType(std::move(*fromEntry));
    0:12.57                                    ^         ~~~~~~~~~~~~~~~~~~~~~
    0:12.57 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/nsTHashtable.h:478:13: note: in instantiation of member function 'nsTHashtable<const mozilla::SheetLoadDataHashKey>::s_CopyEntry' requested here
    0:12.57           : s_CopyEntry,
    0:12.57             ^
    0:12.57 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/nsTHashtable.h:163:16: note: in instantiation of member function 'nsTHashtable<const mozilla::SheetLoadDataHashKey>::Ops' requested here
    0:12.57       : mTable(Ops(), sizeof(EntryType), PLDHashTable::kDefaultInitialLength) {}
    0:12.57                ^
    0:12.57 /home/emilio/src/moz/gecko-2/layout/style/Loader.cpp:359:9: note: in instantiation of member function 'nsTHashtable<const mozilla::SheetLoadDataHashKey>::nsTHashtable' requested here
    0:12.57 Loader::Loader()
    0:12.57         ^
    0:12.57 /home/emilio/src/moz/gecko-2/obj-debug-no-sccache/dist/include/mozilla/css/Loader.h:97:3: note: copy constructor is implicitly deleted because 'SheetLoadDataHashKey' has a user-declared move constructor
    0:12.57   SheetLoadDataHashKey(SheetLoadDataHashKey&& toMove)
    0:12.57   ^
    0:13.08 1 error generated

This one was easier to fix though. Not too proud of this one.

Differential Revision: https://phabricator.services.mozilla.com/D77830