Bug 1732245 - Silence the unused-but-set-variable warning in dom/webauthn. r=keeler
dom/webauthn/WinWebAuthnManager.cpp(274,11): error: variable 'winAttestation' set but not used [-Werror,-Wunused-but-set-variable]
    DWORD winAttestation = WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_ANY;
          ^
dom/webauthn/WinWebAuthnManager.cpp(529,9): error: variable 'winAttachment' set but not used [-Werror,-Wunused-but-set-variable]
  DWORD winAttachment = WEBAUTHN_AUTHENTICATOR_ATTACHMENT_ANY;
        ^

Differential Revision: https://phabricator.services.mozilla.com/D126449