Bug 1317880 - Move adjust and thirdparty jars into GECKOVIEW_JARS to fix annotation processing on a CLOSED TREE r=sebastian, a=gchang
GECKOVIEW_JARS contains two Adjust classes (within constants.jar). These depend on the rest of adjust,
which was previously within FENNEC_JARS. Without the remaining adjust jars being on the classpath during
annotation processing for GECKOVIEW_JARS, we are unable to correctly process those Adjust classes
(i.e. we get a NoClassDefFoundError).

The minimal fix is to process adjust as part of GECKOVIEW_JARS. Because adjust depends on HttpClientLib,
we also need to move the relevant jars into GECKOVIEW_JARS too (sync-thirparty contains HttpClientLib).

This will probably require further untangling, this is a minimal patch to allow beta to actually build.

MozReview-Commit-ID: DLtazTrg3hV

--HG--
extra : source : 6b7c1986d7ecc870c32e10b44f1a128b41f44c59