Bug 1733034 - Ignore unreachable-code-loop-increment in TestFlatten. r=dom-workers-and-storage-reviewers,janv
dom/quota/test/gtest/TestFlatten.cpp:18:3: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
  for (const auto& item : Flatten<int>(nsTArray<int>{})) {
  ^~~
dom/quota/test/gtest/TestFlatten.cpp:26:3: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
  for (const auto& item : Flatten<int>(nsTArray<CopyableTArray<int>>{})) {
  ^~~
dom/quota/test/gtest/TestFlatten.cpp:34:3: error: loop will run at most once (loop increment never executed) [-Werror,-Wunreachable-code-loop-increment]
  for (const auto& item :
  ^~~

clang figures out that the loop is not going to execute, which is the
whole point of the test.

Differential Revision: https://phabricator.services.mozilla.com/D126874