Bug 1754295 part 3: Fix non-unified build errors in layout/tables, and mark it as safe to build in non-unified mode. r=boris
This patch fixes the following build error:
layout/tables/FixedTableLayoutStrategy.cpp:86:31: error: incomplete type 'nsLayoutUtils' named in nested name specifier

I'm also removing the "DEBUG_TABLE_STRATEGY_off" definition from the contextual
section of moz.build, because that symbol is never used. (It's never mentioned
anywhere else in our codebase; it must have controlled some long-since-removed
code).

Differential Revision: https://phabricator.services.mozilla.com/D138217