Bug 1374389: Prevent compilation error due to object size being too big. r=glandium
Prevent on Windows the error:
fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj

MozReview-Commit-ID: 8j0fT38gkAZ

--HG--
extra : rebase_source : fbd220a208d09023f5ff6f115404349a9d97a7f8