Bug 1743082 - While at it, fix inert-node-is-uneditable.html and inert-inlines.html. r=sefeng
Failed in Chrome and Firefox with:

  marionette_driver.errors.InvalidArgumentException: Expected 'x' ([object Number] 187.5) to be an Integer

Because of fractional widths. Round to deal with it.

Depends on D134964

Differential Revision: https://phabricator.services.mozilla.com/D134965