Bug 1690701 Part 1.5 - Check |frame| instead of |styleFrame| for abspos in GetUnretargetedOffsetsFor(). r=emilio
When `aElement` is a <table>, `styleFrame` is the inner table frame. It
has the abspos style, but not the `NS_FRAME_OUT_OF_FLOW bit`. The bit is
set on the table wrapper frame in the `frame` variable.

When determining whether the <table> is absolutely positioned, we should
check `frame` instead of `styleFrame`. Otherwise we'll break <table>
element's offsetParent property after applying Part 2.

Without this patch, running `./mach test dom/html/test/test_bug375003-1.html`
can generate the following exception.

  dom/html/test/test_bug375003-1.html | uncaught exception -
  TypeError: can't access property "id", p is null at
  t3@http://mochi.test:8888/tests/dom/html/test/test_bug375003-1.html:39:3

Differential Revision: https://phabricator.services.mozilla.com/D106746