Bug 1212527 - Set background color to NSColor before calling showDefinitionForAttributedString on 10.11. r=mstange
When calling showDefinitionforAttributedString on OSX 10.11, it always return error due to the following exception.

Exception: decodeObjectForKey: class "TitlebarAndBackgroundColor" not loaded or does not exist

So before calling it, we set temporary color value, then restore color after calling it.

MozReview-Commit-ID: 1YeY6X1W6AV

--HG--
extra : rebase_source : 1bfafdb24f7d6df0ad2552b786b8af84b71cc28a