Bug 1611536 - Add stdint.h include for fixed-width integer types r=Ehsan
musl libc does not define these types through the other headers
included by this file, which causes errors when building RemoteUtils.cpp
(which indirectly includes nsCharTraits.h):

	error: unknown type name 'int32_t'

Differential Revision: https://phabricator.services.mozilla.com/D61040

--HG--
extra : moz-landing-system : lando