Bug 1164658 - disable test_web_channel.js for thunderbird, as it requires weave which thunderbird doesn't have. r=markh
TEST-UNEXPECTED-FAIL | services/fxaccounts/tests/xpcshell/test_web_channel.js | xpcshell return code: 0
TypeError: Cc['@mozilla.org/weave/service;1'] is undefined at resource://gre/modules/FxAccountsWebChannel.jsm:227

--HG--
extra : rebase_source : 2f1822d26743480d2377e343288ae0edd2428330