Bug 1731098 - Include nsIThread in TestMultiplexInputStream.cpp r=xpcom-reviewers,nika
When adding new gtests I came across this build failure:

```
 0:12.59 In file included from Unified_cpp_xpcom_tests_gtest2.cpp:2:
 0:12.59 /home/kriswright/src/mozilla-unified/xpcom/tests/gtest/TestMultiplexInputStream.cpp:349:45: error: no viable conversion from 'nsCOMPtr<nsIThread>' to 'nsIEventTarget *'
```

It looks like this file needs to include nsIThread in its #includes.

Differential Revision: https://phabricator.services.mozilla.com/D125851