Bug 1832984 - Apply upstream Breakpad fix for C++20 std::allocator<T>::pointer error. r=gsvelto
`std::allocator<T>::pointer` and related types were removed in C++20, so move to `std::allocator_traits` which has been available since C++11. Apply upstream Breakpad fix for C++20 std::allocator<T>::pointer error:

https://github.com/google/breakpad/commit/5c4b5d89e494753656fc84c5266519478ebb448c

We don't need to create a local patch for this change because this change is from upstream. When/if we update our copy of Breakpad again, overwriting this change is OK.

toolkit/crashreporter/google-breakpad/src/common/memory_allocator.h:164:39: error: no type named 'pointer' in 'std::allocator<MDMemoryDescriptor>'
   typedef typename std::allocator<T>::pointer pointer;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

Differential Revision: https://phabricator.services.mozilla.com/D177968