fix bug 203450 jarevil.c:345: warning: implicit declaration of function \   `__CERT_AddTempCertToPerm'
Obviously missing a declaration somewhere.

r=jpierr, wtc